// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/norun9/Hybird/internal/api/infra/repository"
	"github.com/norun9/Hybird/internal/api/interfaces"
	"github.com/norun9/Hybird/internal/api/usecase"
	"github.com/norun9/Hybird/pkg/config"
	"github.com/norun9/Hybird/pkg/db"
)

// Injectors from wire.go:

func InitializeRestHandler(dbConfig config.DBConfig) interfaces.IRestHandler {
	sqlDB := db.NewDB(dbConfig)
	iMessageRepository := repository.NewMessageRepository(sqlDB)
	iMessageInputBoundary := usecase.NewMessageInteractor(iMessageRepository)
	v := interfaces.GetMapRoute(iMessageInputBoundary)
	iRestHandler := interfaces.NewRestHandler(v)
	return iRestHandler
}

// wire.go:

var inputBoundarySet = wire.NewSet(db.NewDB, repository.NewMessageRepository, usecase.NewMessageInteractor)

var routeMapSet = wire.NewSet(
	inputBoundarySet, interfaces.GetMapRoute,
)
