// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/norun9/Hybird/internal/api/interfaces"
	"github.com/norun9/Hybird/internal/api/interfaces/controller"
	repository2 "github.com/norun9/Hybird/internal/api/interfaces/gateways/repository"
	"github.com/norun9/Hybird/internal/api/usecase"
	"github.com/norun9/Hybird/pkg/config"
	"github.com/norun9/Hybird/pkg/db"
)

// Injectors from wire.go:

func InitializeRestHandler(dbConfig config.DBConfig) interfaces.IRestHandler {
	sqlDB := db.NewDB(dbConfig)
	client := db.NewDBClient(sqlDB)
	iMessageRepository := repository2.NewMessageRepository(client)
	paging := repository2.NewPaging()
	iMessageInputBoundary := usecase.NewMessageInteractor(iMessageRepository, paging)
	iMessageController := controller.NewMessageController(iMessageInputBoundary)
	v := interfaces.GetMapRoute(iMessageController)
	iRestHandler := interfaces.NewRestHandler(v)
	return iRestHandler
}

// wire.go:

var inputBoundarySet = wire.NewSet(db.NewDB, db.NewDBClient, repository2.NewMessageRepository, usecase.NewMessageInteractor)
