sqlboiler:
	sqlboiler mysql --pkgname dbmodels --add-soft-deletes --no-hooks --struct-tag-casing snake --output "./lib/dbmodels" --wipe --config ./sqlboiler.toml
	go test ./lib/dbmodels/*.go -test.config ../../sqlboiler.toml