version: "3.8"

services:
  air:
    container_name: "air"
    build:
      context: "./backend"
      dockerfile: "../docker/dev/air/Dockerfile"
    command: "air -c .air.toml"
    working_dir: "/app/go/dev"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/go/dev
    depends_on:
      - db
  db:
    container_name: "mysql"
    platform: "linux/amd64"
    build:
      context: "."
      dockerfile: "docker/dev/db/Dockerfile"
    cap_add:
      - SYS_NICE
    command: |
      --default-authentication-plugin=mysql_native_password
      --default-time-zone='Asia/Tokyo'
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: testdb
      MYSQL_USER: hybird
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./backend/db/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: [ "CMD", "mysql", "-h127.0.0.1", "-P3306", "-uhybird", "-e", "quit" ]
volumes:
  db: