version: "3.8"

services:
  dynamodb:
    image: "amazon/dynamodb-local"
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    volumes:
      - dynamodb:/home/dynamodblocal
  awscli:
    container_name: awscli
    build:
      context: "./docker/dev/awscli"
      dockerfile: Dockerfile
    entrypoint: [ "" ]
    tty: true
    command:
      - /bin/sh
    volumes:
      - ./bin:/usr/app
      - ~/.aws:/root/.aws
# aws --profile default dynamodb list-tables --region ap-northeast-1 --endpoint-url http://dynamodb:8000

# aws --profile default dynamodb create-table \
#  --table-name Connections \
#  --attribute-definitions \
#    AttributeName=ConnectionId,AttributeType=S \
#  --key-schema \
#    AttributeName=ConnectionId,KeyType=HASH \
#  --billing-mode PAY_PER_REQUEST \
#  --endpoint-url http://dynamodb:8000
volumes:
  dynamodb:
  bin: