version = 0.1
[default.deploy.parameters]
stack_name = "hybird"
resolve_s3 = true
s3_prefix = "hybird"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HybirdGinFunction=730335200646.dkr.ecr.ap-northeast-1.amazonaws.com/hybird323144d4/hybirdginfunction1b39df48repo"]
