env:
  name:

dev:
  gin:
    mode: "debug"
  http:
    cors:
      allowed_origins:
        - "http://localhost:3100"
  db:
    host: "mysql"
    user: "hybird"
    pass: "test"
    name: "testdb"
prd:
  gin:
    mode: "release"
  http:
    cors:
      allowed_origins:
        - "http://localhost:3100"
  db:
    host:
    user:
    pass:
    name: