env:
  name:

dev:
  http:
    cors:
      allowed_origin: "http://localhost:3100"
  db:
    host: "mysql"
    user: "hybird"
    pass: "test"
    name: "testdb"
prd:
  http:
    cors:
      allowed_origin:
  db:
    host:
    user:
    pass:
    name: