#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -z "$(git diff --cached --name-only frontend)" ]; then
  echo "[skipping]frontend - no changes detected"
else
  cd frontend
  yarn lint-staged --relative
  cd ../..
fi