name: SSG Deployment
on: workflow_dispatch

permissions:
  id-token: write

env:
  AWS_REGION: "ap-northeast-1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OICD_ROLE_NAME }}"
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: |
          yarn build
          ls -la out
      - name: Deploy
        run: |
          echo "AWS S3 sync"
          aws s3 sync --region ap-northeast-1 ./out s3://${{ secrets.AWS_S3_BUCKET }} --delete
      - name: Clear CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CF_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ env.AWS_REGION }}
